const voices = [
  {
    name: "abril",
    language: "Catalan",
    languageCode: "ca-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "abyasa",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal"],
  },
  {
    name: "adipati",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal"],
  },
  {
    name: "aditi",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "adriana",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal"],
  },
  {
    name: "afroditi",
    language: "Greek",
    languageCode: "el-GR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "agueda",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "agung",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aicelle",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal"],
  },
  {
    name: "aileen",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aisha",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal"],
  },
  {
    name: "aitor",
    language: "Basque",
    languageCode: "eu-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ajay",
    language: "Malayalam",
    languageCode: "ml-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "akira",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal"],
  },
  {
    name: "aksel",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alain",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "alan",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "alberto",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alejandra",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alessandra",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "aletta",
    language: "English (South African accent)",
    languageCode: "en-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alexandru",
    language: "Romanian",
    languageCode: "ro-RO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alfonso",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "alfred",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ali",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal"],
  },
  {
    name: "alina",
    language: "Romanian",
    languageCode: "ro-RO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "almudena",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "alonso",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "altynai",
    language: "Kazakh",
    languageCode: "kk-KZ",
    styles: ["normal"],
  },
  {
    name: "amada",
    language: "Galician",
    languageCode: "gl-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "amanda",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "amber",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "amina",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "amitabh",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "amleset",
    language: "Amharic",
    languageCode: "am-ET",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "amy",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "anders",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal"],
  },
  {
    name: "andreas",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "andrey",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "andrzej",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal"],
  },
  {
    name: "angharad",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "angus",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "anil",
    language: "Kannada",
    languageCode: "kn-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ankhmaa",
    language: "Mongolian",
    languageCode: "mn-MN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "anong",
    language: "Thai",
    languageCode: "th-TH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "anouk",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "antoine",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "antonella",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "antonio",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "anwen",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aoife",
    language: "Irish",
    languageCode: "ga-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aparna",
    language: "Tamil",
    languageCode: "ta-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "arben",
    language: "Albanian",
    languageCode: "sq-AL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "archie",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ariana",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "ariane",
    language: "French (Swiss)",
    languageCode: "fr-CH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "armando",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "armin",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "arnaldo",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "arpita",
    language: "Bangla (West Bengal Indian accent)",
    languageCode: "bn-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "arvydas",
    language: "Lithuanian",
    languageCode: "lt-LT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "asha",
    language: "Gujarati",
    languageCode: "gu-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "ashley",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aslak",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal"],
  },
  {
    name: "astrid",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "asyifa",
    language: "Sundanese",
    languageCode: "su-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "atep",
    language: "Sundanese",
    languageCode: "su-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "audrey",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "aurora",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ayami",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ayelet",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "badrai",
    language: "Pashto",
    languageCode: "ps-AF",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "baihe",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "banyu",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal"],
  },
  {
    name: "baoguo",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "barbora",
    language: "Czech",
    languageCode: "cs-CZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bas",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "beatrice",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "beatriz",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "bedwyr",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ben",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["normal"],
  },
  {
    name: "benedita",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "berik",
    language: "Kazakh",
    languageCode: "kk-KZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bernardo",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "besa",
    language: "Albanian",
    languageCode: "sq-AL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bethan",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bethari",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "betty",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "beverly",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bhavana",
    language: "Kannada",
    languageCode: "kn-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bianca",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bill",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "birgit",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "biswajit",
    language: "Bangla (West Bengal Indian accent)",
    languageCode: "bn-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "blanca",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bo",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bo-young",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bonnie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "boris",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "brad",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "brian",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "bridget",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "brigitte",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "britney",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "britta",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bronagh",
    language: "English (Irish accent)",
    languageCode: "en-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "brooke",
    language: "English (New Zealand accent)",
    languageCode: "en-NZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "bruce",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "bruno",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "budiwati",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal"],
  },
  {
    name: "cabdi",
    language: "Somali",
    languageCode: "so-SO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "carmen",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "carol",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "cecilia",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "celine",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal"],
  },
  {
    name: "cerys",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "cesar",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "chad",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "chae-won",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal"],
  },
  {
    name: "chao",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "charles",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "charlize",
    language: "English (South African accent)",
    languageCode: "en-ZA",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "chen",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal"],
  },
  {
    name: "cheng",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "chiara",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "chico",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "childroid",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "chloe",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "chris",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["normal"],
  },
  {
    name: "chuck",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "cillian",
    language: "English (Irish accent)",
    languageCode: "en-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "cindy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "claudine",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "clive",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "colette",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "conchita",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "connie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "connor",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "conrad",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "corazon",
    language: "Maltese",
    languageCode: "mt-MT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "cordelia",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "cyrille",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "da-hee",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal"],
  },
  {
    name: "dafydd",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dagmara",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "daniel",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "danuta",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "daoming",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "daphne",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "darya",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "daud",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "david",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "dawei",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dearbhla",
    language: "Irish",
    languageCode: "ga-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "debbie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "deepika",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "desislava",
    language: "Bulgarian",
    languageCode: "bg-BG",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "didier",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "diego",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "dieter",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "dietrich",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dilawar",
    language: "Pashto",
    languageCode: "ps-AF",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dilhani",
    language: "Sinhala",
    languageCode: "si-LK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dilip",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "diljit",
    language: "Punjabi",
    languageCode: "pa-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "dilnoza",
    language: "Uzbek",
    languageCode: "uz-UZ",
    styles: ["normal"],
  },
  {
    name: "dimitris",
    language: "Greek",
    languageCode: "el-GR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dolores",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dominic",
    language: "Maltese",
    languageCode: "mt-MT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dong-min",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "doron",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal"],
  },
  {
    name: "dorothy",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "dulce",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "dustin",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "eamon",
    language: "Irish",
    languageCode: "ga-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "eddie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "eduardo",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "edward",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "eevi",
    language: "Finnish",
    languageCode: "fi-FI",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "einar",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "eiza",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ekaterina",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal"],
  },
  {
    name: "eleni",
    language: "Greek",
    languageCode: "el-GR",
    styles: ["literal", "normal"],
  },
  {
    name: "eliana",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "elisabeth",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "ellie",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "elma",
    language: "English (Filipino accent)",
    languageCode: "en-PH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "elsa",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "emilia",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "emilio",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "emily",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "emma",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "enrico",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "enrique",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "erez",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal"],
  },
  {
    name: "eric",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "erik",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "erika",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "esmeralda",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "estelle",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "eszter",
    language: "Hungarian",
    languageCode: "hu-HU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "fabrice",
    language: "French (Belgian)",
    languageCode: "fr-BE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "fabrizio",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "fahad",
    language: "Urdu",
    languageCode: "ur-PK",
    styles: ["literal", "normal"],
  },
  {
    name: "famke",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "farah",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "farhat",
    language: "Kazakh",
    languageCode: "kk-KZ",
    styles: ["normal"],
  },
  {
    name: "fatma",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal"],
  },
  {
    name: "federica",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal"],
  },
  {
    name: "felicity",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "felipe",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "feng",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal"],
  },
  {
    name: "fernanda",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "fernando",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "fiona",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "flora",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "florian",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "floyd",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "francisco",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "franka",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "fransje",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "franz",
    language: "German (Austrian)",
    languageCode: "de-AT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "freja",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "fritzi",
    language: "German (Austrian)",
    languageCode: "de-AT",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "fulvia",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "fumiko",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "fyodor",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gabrielle",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gael",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "gail",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "galina",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ganbaatar",
    language: "Mongolian",
    languageCode: "mn-MN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gareth",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gary",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "george",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "gerard",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gerhard",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gertrud",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gijsbert",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "gina",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "girum",
    language: "Amharic",
    languageCode: "am-ET",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gisele",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "giuseppe",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gloria",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gonzalo",
    language: "Galician",
    languageCode: "gl-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gopal",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "grace",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "graham",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "greg",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "greta",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gretel",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "guadalupe",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "guardbot",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "guillaume",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gulshat",
    language: "Kazakh",
    languageCode: "kk-KZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gulzar",
    language: "Punjabi",
    languageCode: "pa-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "gustaf",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal"],
  },
  {
    name: "gustavo",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gwen",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "gwyneth",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hadas",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["normal"],
  },
  {
    name: "hai",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal"],
  },
  {
    name: "haifa",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hans",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "hanyu",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "harriet",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "harrison",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "harry",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "hector",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hedvig",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "heidi",
    language: "German (Swiss)",
    languageCode: "de-CH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "heike",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "heinz",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "helen",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "helmut",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "hendrika",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "henriqueta",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hetang",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hideaki",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hilde",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hoa",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal"],
  },
  {
    name: "holly",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "horacio",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hua",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hye-kyo",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hye-rim",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "hywel",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ian",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "iben",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ieuan",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ignacio",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "igor",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal"],
  },
  {
    name: "ilse",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "imran",
    language: "Urdu",
    languageCode: "ur-PK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "in-guk",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "indah",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal"],
  },
  {
    name: "ines",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "inez",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "inger",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal"],
  },
  {
    name: "ingrid",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal"],
  },
  {
    name: "ingvar",
    language: "Icelandic",
    languageCode: "is-IS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "intan",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal"],
  },
  {
    name: "ioana",
    language: "Romanian",
    languageCode: "ro-RO",
    styles: ["literal", "normal"],
  },
  {
    name: "irina",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "isabella",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "isyana",
    language: "Javanese",
    languageCode: "jv-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ivan",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal"],
  },
  {
    name: "ivana",
    language: "Slovak",
    languageCode: "sk-SK",
    styles: ["literal", "normal"],
  },
  {
    name: "ivy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "iwona",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jack",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "jackie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jackson",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jacques",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jae-hyun",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jairus",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal"],
  },
  {
    name: "james",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "janez",
    language: "Slovene",
    languageCode: "sl-SI",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jasna",
    language: "Croatian",
    languageCode: "hr-HR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "javier",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jean",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "jeff",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "jennifer",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "jens",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jessica",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["normal"],
  },
  {
    name: "ji-dan",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ji-sung",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ji-yeon",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jianbin",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jianhua",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jing",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "joanna",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "joaquim",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal"],
  },
  {
    name: "jochem",
    language: "Afrikaans",
    languageCode: "af-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jodie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "john",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jomari",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal"],
  },
  {
    name: "joon-gi",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal"],
  },
  {
    name: "jordi",
    language: "Catalan",
    languageCode: "ca-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jorge",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "josephine",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "juana",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "judy",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jueming",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "juha",
    language: "Finnish",
    languageCode: "fi-FI",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "julia",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "julie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "juliette",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal"],
  },
  {
    name: "julio",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "juraj",
    language: "Slovak",
    languageCode: "sk-SK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "jurga",
    language: "Lithuanian",
    languageCode: "lt-LT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "justin",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "justine",
    language: "French (Belgian)",
    languageCode: "fr-BE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "justyna",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal"],
  },
  {
    name: "jutta",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kaarel",
    language: "Estonian",
    languageCode: "et-EE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kaige",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal"],
  },
  {
    name: "kaori",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kar-ling",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kareena",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "karen",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "karim",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal"],
  },
  {
    name: "karthika",
    language: "Malayalam",
    languageCode: "ml-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "kasumi",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal"],
  },
  {
    name: "katarzyna",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal"],
  },
  {
    name: "kate",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "kayla",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kei",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "keira",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "keith",
    language: "English (New Zealand accent)",
    languageCode: "en-NZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kelly",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "kemal",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal"],
  },
  {
    name: "kenichi",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal"],
  },
  {
    name: "kenji",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kerstin",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "khaled",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kim",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kimberly",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "kiril",
    language: "Bulgarian",
    languageCode: "bg-BG",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kirk",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kjersti",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal"],
  },
  {
    name: "klara",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "klaus",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "koen",
    language: "Dutch (Flemish)",
    languageCode: "nl-BE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kong-sang",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kristaps",
    language: "Latvian",
    languageCode: "lv-LV",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "krisztina",
    language: "Hungarian",
    languageCode: "hu-HU",
    styles: ["literal", "normal"],
  },
  {
    name: "kuniko",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "kylie",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "lada",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ladislav",
    language: "Czech",
    languageCode: "cs-CZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "laetitia",
    language: "French (Belgian)",
    languageCode: "fr-BE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "laia",
    language: "Catalan",
    languageCode: "ca-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lakshmi",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "lalita",
    language: "Telugu",
    languageCode: "te-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lars",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "laura",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal"],
  },
  {
    name: "laurent",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "lazar",
    language: "Serbian",
    languageCode: "sr-RS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lazar-latin",
    language: "Serbian",
    languageCode: "sr-RS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leandra",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leila",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leire",
    language: "Basque",
    languageCode: "eu-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lenny",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leonardo",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leonor",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal"],
  },
  {
    name: "lewis",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "leyla",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "lhakpa",
    language: "Nepali",
    languageCode: "ne-NP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "liam",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "lieve",
    language: "Dutch (Flemish)",
    languageCode: "nl-BE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "lihua",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "linda",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lindsey",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "linnea",
    language: "Finnish",
    languageCode: "fi-FI",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "lior",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lisa",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "liselotte",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "liv",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal"],
  },
  {
    name: "livia",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "liying",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "llewellyn",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lola",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "loredana",
    language: "Romanian",
    languageCode: "ro-RO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lorenzo",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lothar",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lotte",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "louise",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luc",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luca",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lucia",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "luciano",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lucienne",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lucy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ludovica",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luigi",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luis",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luna",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "luodan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "lupita",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "lurdes",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "luz",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal"],
  },
  {
    name: "lynne",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "maaike",
    language: "Dutch (Flemish)",
    languageCode: "nl-BE",
    styles: ["literal", "normal"],
  },
  {
    name: "maartje",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "macarena",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "madalena",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "magda",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "maggie",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "mahir",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal"],
  },
  {
    name: "mahiya",
    language: "Bangla (Bangladesh accent)",
    languageCode: "bn-BD",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "majida",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "malcolm",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "malee",
    language: "Thai",
    languageCode: "th-TH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "malin",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal"],
  },
  {
    name: "man-chi",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "manasi",
    language: "Gujarati",
    languageCode: "gu-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "manny",
    language: "English (Filipino accent)",
    languageCode: "en-PH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "manuel",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "marcela",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "marcelle",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "margarida",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal"],
  },
  {
    name: "margarita",
    language: "Spanish (Puerto Rican accent)",
    languageCode: "es-PR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "margot",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "maricel",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal"],
  },
  {
    name: "mariko",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "mario",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal"],
  },
  {
    name: "marion",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "marisol",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mark",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "marlene",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "martin",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "martina",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mary",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "marzena",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal"],
  },
  {
    name: "masha",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "matt",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "matteo",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "matthias",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "matthieu",
    language: "French (Swiss)",
    languageCode: "fr-CH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "maurice",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mawar",
    language: "Indonesian",
    languageCode: "id-ID",
    styles: ["literal", "normal"],
  },
  {
    name: "mawra",
    language: "Urdu",
    languageCode: "ur-PK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mayang",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "megan",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mehar",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "mei",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "meilan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal"],
  },
  {
    name: "meiling",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "melanie",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal"],
  },
  {
    name: "melissa",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["normal"],
  },
  {
    name: "mengyao",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "menzi",
    language: "Zulu",
    languageCode: "zu-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mercedes",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mia",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "mickey",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "miguel",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "mike",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "milica",
    language: "Serbian",
    languageCode: "sr-RS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "milica-latin",
    language: "Serbian",
    languageCode: "sr-RS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "min-ho",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal"],
  },
  {
    name: "minh",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mireia",
    language: "Catalan",
    languageCode: "ca-ES",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "missy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "mohnish",
    language: "Marathi",
    languageCode: "mr-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mojca",
    language: "Slovene",
    languageCode: "sl-SI",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "monika",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal"],
  },
  {
    name: "morena",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "morgan",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "moritz",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "mujo",
    language: "Bosnian",
    languageCode: "bs-BA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "murali",
    language: "Malayalam",
    languageCode: "ml-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "murat",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "myfanwy",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nabha",
    language: "Kannada",
    languageCode: "kn-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "nadezhda",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nam",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal"],
  },
  {
    name: "nancy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nandi",
    language: "Zulu",
    languageCode: "zu-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "natalia",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "navneet",
    language: "Punjabi",
    languageCode: "pa-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "nazan",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal"],
  },
  {
    name: "neerja",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nelson",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nga",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ngina",
    language: "Swahili",
    languageCode: "sw-KE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nicole",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "niklas",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nikolai",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nina",
    language: "Macedonian",
    languageCode: "mk-MK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nino",
    language: "Georgian",
    languageCode: "ka-GE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nisa",
    language: "Khmer",
    languageCode: "km-KH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nitesh",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "nora",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nune",
    language: "Armenian",
    languageCode: "hy-AM",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nuria",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "nurit",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal"],
  },
  {
    name: "obinna",
    language: "English (Nigerian accent)",
    languageCode: "en-NG",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "octavio",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "odette",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "oksana",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal"],
  },
  {
    name: "ole",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal"],
  },
  {
    name: "oleksandr",
    language: "Ukrainian",
    languageCode: "uk-UA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "olena",
    language: "Ukrainian",
    languageCode: "uk-UA",
    styles: ["literal", "normal"],
  },
  {
    name: "olga",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal"],
  },
  {
    name: "olivia",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "olivier",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "ollie",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "orla",
    language: "English (Irish accent)",
    languageCode: "en-IE",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "ornella",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal"],
  },
  {
    name: "outhine",
    language: "Lao",
    languageCode: "lo-LA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "oylum",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal"],
  },
  {
    name: "padma",
    language: "Marathi",
    languageCode: "mr-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "pak-chi",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "paloma",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pamela",
    language: "English (Canadian)",
    languageCode: "en-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "paola",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "pascal",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal"],
  },
  {
    name: "patti",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "paul",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "paulo",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pedro",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal"],
  },
  {
    name: "petra",
    language: "Czech",
    languageCode: "cs-CZ",
    styles: ["literal", "normal"],
  },
  {
    name: "phantom",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pierre",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "piet",
    language: "English (South African accent)",
    languageCode: "en-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pilar",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal"],
  },
  {
    name: "pille",
    language: "Estonian",
    languageCode: "et-EE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "piolo",
    language: "Filipino",
    languageCode: "fil-PH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pooja",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "prabhat",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "pratik",
    language: "Gujarati",
    languageCode: "gu-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "preeti",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "prosenjit",
    language: "Bangla (West Bengal Indian accent)",
    languageCode: "bn-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "quan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "quang",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal"],
  },
  {
    name: "rafael",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "raffaella",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rahul",
    language: "Kannada",
    languageCode: "kn-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "rajesh",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "ramakrishna",
    language: "Telugu",
    languageCode: "te-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ramesh",
    language: "Gujarati",
    languageCode: "gu-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "ramona",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rana",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal"],
  },
  {
    name: "raymond",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rebecca",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "regina",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "reza",
    language: "Persian",
    languageCode: "fa-IR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rhonda",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "rhys",
    language: "Welsh",
    languageCode: "cy-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rie",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "riyanto",
    language: "Javanese",
    languageCode: "jv-ID",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "roberto",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal"],
  },
  {
    name: "robin",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "robovoice",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rodney",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "rodrigo",
    language: "Spanish (Puerto Rican accent)",
    languageCode: "es-PR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rogerio",
    language: "Portuguese (European)",
    languageCode: "pt-PT",
    styles: ["literal", "normal"],
  },
  {
    name: "rohit",
    language: "Marathi",
    languageCode: "mr-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "rolanda",
    language: "Afrikaans",
    languageCode: "af-ZA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "romain",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ronald",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "roos",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "rory",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rosalind",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rosaria",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rose",
    language: "English (New Zealand accent)",
    languageCode: "en-NZ",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "ross",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "rubem",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "russel",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "ruth",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ryan",
    language: "English (Canadian)",
    languageCode: "en-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "saara",
    language: "Finnish",
    languageCode: "fi-FI",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sally",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "salman",
    language: "Bangla (Bangladesh accent)",
    languageCode: "bn-BD",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "samira",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sanam",
    language: "Urdu",
    languageCode: "ur-PK",
    styles: ["literal", "normal"],
  },
  {
    name: "sanath",
    language: "Sinhala",
    languageCode: "si-LK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sanda",
    language: "Burmese",
    languageCode: "my-MM",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sandra",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sangeeta",
    language: "Marathi",
    languageCode: "mr-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "santiago",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "saoirse",
    language: "English (Irish accent)",
    languageCode: "en-IE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sarah",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "saskia",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "seble",
    language: "Amharic",
    languageCode: "am-ET",
    styles: ["literal", "normal"],
  },
  {
    name: "seo-yeon",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "serge",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sergey",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shahana",
    language: "Marathi",
    languageCode: "mr-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shane",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shannon",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["normal"],
  },
  {
    name: "shavkat",
    language: "Uzbek",
    languageCode: "uz-UZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shilpa",
    language: "English (Indian accent)",
    languageCode: "en-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "shirley",
    language: "English (Scottish Accent)",
    languageCode: "en-GB-SCT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shishi",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shohreh",
    language: "Persian",
    languageCode: "fa-IR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "shruti",
    language: "Tamil",
    languageCode: "ta-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "shuang",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sibel",
    language: "Turkish",
    languageCode: "tr-TR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sidse",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal"],
  },
  {
    name: "signe",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "sigrid",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal"],
  },
  {
    name: "silvana",
    language: "Spanish (Mexican)",
    languageCode: "es-MX",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "silvia",
    language: "Catalan",
    languageCode: "ca-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "siwan",
    language: "English (Welsh Accent)",
    languageCode: "en-GB-WLS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "soledad",
    language: "Spanish (Castilian)",
    languageCode: "es-ES",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "solveig",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "somsak",
    language: "Thai",
    languageCode: "th-TH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sonja",
    language: "Norwegian",
    languageCode: "nb-NO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "sophie",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal"],
  },
  {
    name: "sovath",
    language: "Khmer",
    languageCode: "km-KH",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "spencer",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "steinunn",
    language: "Icelandic",
    languageCode: "is-IS",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "stellan",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal"],
  },
  {
    name: "steve",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "suada",
    language: "Bosnian",
    languageCode: "bs-BA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "suleiman",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "sunerah",
    language: "Bangla (West Bengal Indian accent)",
    languageCode: "bn-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "sushma",
    language: "Hindi",
    languageCode: "hi-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "suwanna",
    language: "Thai",
    languageCode: "th-TH",
    styles: ["literal", "normal"],
  },
  {
    name: "svitlana",
    language: "Ukrainian",
    languageCode: "uk-UA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tadeusz",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tae-hee",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal"],
  },
  {
    name: "takeshi",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "takuya",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tamagne",
    language: "Amharic",
    languageCode: "am-ET",
    styles: ["literal", "normal"],
  },
  {
    name: "tamar",
    language: "Hebrew",
    languageCode: "he-IL",
    styles: ["literal", "normal"],
  },
  {
    name: "tamsin",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal"],
  },
  {
    name: "tara",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tatiana",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "taufan",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tenzing",
    language: "Nepali",
    languageCode: "ne-NP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "thandiwe",
    language: "English (Nigerian accent)",
    languageCode: "en-NG",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "theodore",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "thiago",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tigran",
    language: "Armenian",
    languageCode: "hy-AM",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tiina",
    language: "Finnish",
    languageCode: "fi-FI",
    styles: ["literal", "normal"],
  },
  {
    name: "timmy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "tina",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "tofiq",
    language: "Azerbaijani",
    languageCode: "az-AZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tom",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "tomasz",
    language: "Polish",
    languageCode: "pl-PL",
    styles: ["literal", "normal"],
  },
  {
    name: "tommaso",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tomoka",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tonkham",
    language: "Lao",
    languageCode: "lo-LA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tony",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "tornike",
    language: "Georgian",
    languageCode: "ka-GE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tracy",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "trine",
    language: "Danish",
    languageCode: "da-DK",
    styles: ["literal", "normal"],
  },
  {
    name: "trinh",
    language: "Vietnamese",
    languageCode: "vi-VN",
    styles: ["literal", "normal"],
  },
  {
    name: "troy",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "tuah",
    language: "Malaysian",
    languageCode: "ms-MY",
    styles: ["literal", "normal"],
  },
  {
    name: "uhuru",
    language: "Swahili",
    languageCode: "sw-KE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ulrich",
    language: "German (Standard)",
    languageCode: "de-DE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "uma",
    language: "Malayalam",
    languageCode: "ml-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vadim",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vaida",
    language: "Lithuanian",
    languageCode: "lt-LT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "valentina",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vanessa",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vasco",
    language: "Portuguese (Brazilian)",
    languageCode: "pt-BR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "veerle",
    language: "Dutch (Flemish)",
    languageCode: "nl-BE",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vendela",
    language: "Swedish",
    languageCode: "sv-SE",
    styles: ["literal", "normal"],
  },
  {
    name: "vera",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "victoria",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vijay",
    language: "Tamil",
    languageCode: "ta-IN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vikram",
    language: "Tamil",
    languageCode: "ta-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "vilmos",
    language: "Hungarian",
    languageCode: "hu-HU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vincent",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vincenzo",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "violette",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "virginia",
    language: "English (Australian)",
    languageCode: "en-AU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vittorio",
    language: "Italian",
    languageCode: "it-IT",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vivienne",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vladimir",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "vlatko",
    language: "Macedonian",
    languageCode: "mk-MK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "walter",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal"],
  },
  {
    name: "wanda",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "wei",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "will",
    language: "English (American)",
    languageCode: "en-US",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "willeke",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "willem",
    language: "Dutch",
    languageCode: "nl-NL",
    styles: ["literal", "normal"],
  },
  {
    name: "william",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal"],
  },
  {
    name: "wim",
    language: "Dutch (Flemish)",
    languageCode: "nl-BE",
    styles: ["literal", "normal"],
  },
  {
    name: "wing-yi",
    language: "Chinese (Cantonese)",
    languageCode: "cmn-HK",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "wraith",
    language: "English (British)",
    languageCode: "en-GB",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "xavier",
    language: "French (Canadian)",
    languageCode: "fr-CA",
    styles: ["literal", "normal"],
  },
  {
    name: "xawa",
    language: "Somali",
    languageCode: "so-SO",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ximena",
    language: "Spanish (American)",
    languageCode: "es-US",
    styles: ["literal", "normal"],
  },
  {
    name: "xinyan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "xinyi",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "xiulan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal"],
  },
  {
    name: "yifei",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yili",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yoo-jung",
    language: "Korean",
    languageCode: "ko-KR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yulia",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yumei",
    language: "Chinese (Taiwanese Mandarin)",
    languageCode: "cmn-TW",
    styles: ["literal", "normal"],
  },
  {
    name: "yuqi",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yuri",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yuriko",
    language: "Japanese",
    languageCode: "ja-JP",
    styles: ["literal", "normal"],
  },
  {
    name: "yves",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "yvette",
    language: "French (Metropolitan)",
    languageCode: "fr-FR",
    styles: ["literal", "normal", "ipa", "x-sampa"],
  },
  {
    name: "zareen",
    language: "Punjabi",
    languageCode: "pa-IN",
    styles: ["literal", "normal"],
  },
  {
    name: "zemfira",
    language: "Azerbaijani",
    languageCode: "az-AZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zeya",
    language: "Burmese",
    languageCode: "my-MM",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ziad",
    language: "Arabic",
    languageCode: "ar-XA",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zihan",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "ziwen",
    language: "Chinese (Mandarin)",
    languageCode: "cmn-CN",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zoran",
    language: "Croatian",
    languageCode: "hr-HR",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zoya",
    language: "Russian",
    languageCode: "ru-RU",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zulfiya",
    language: "Uzbek",
    languageCode: "uz-UZ",
    styles: ["literal", "normal", "ipa"],
  },
  {
    name: "zuzana",
    language: "Slovak",
    languageCode: "sk-SK",
    styles: ["literal", "normal", "ipa"],
  },
];
